name: 'Setup Development Environment'
description: 'Composite action to set up Node.js, Python, uv, and pnpm'
author: 'OpenCode Workflow Kit'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '18'
  python-version:
    description: 'Python version to install'
    default: '3.11'
  cache:
    description: 'Whether to cache dependencies'
    default: 'true'
  registry-url:
    description: 'npm registry URL'
    default: 'https://npm.pkg.github.com'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: |
        # Install Python dependencies
        if [ -f "packages/opencode_config/pyproject.toml" ]; then
          cd packages/opencode_config/..
          uv sync
          cd ../../..
        fi

        # Install Node.js dependencies
        pnpm install --frozen-lockfile